---
title: 'DELVE: Data Evidence and Learnings in Viral Epidemics'
timezone: UTC
collections:
  addendums:
    title: Addendums
    output: true
    permalink: "/adhoc/:year/:month/:day/:title:output_ext"
  people:
    title: People
    output: true
  posts:
    title: Posts
    output: true
  reports:
    title: Reports
    output: true
    permalink: "/seminars/:year/:month/:day/:title:output_ext"
  uploads:
    title: Uploads
    output: true
email: your-email@example.com
description: This is the website of the Royal Society DELVE Initiative
baseurl: ''
url: ''
twitter_username: rs-delve
github_username: rs-delve
github:
  edit: true
  repository: rs-delve.github.io
future: true
theme: minima
plugins:
- jekyll-feed
