---
title: 'Royal Society DELVE Initiative'
timezone: UTC
collections:
  addendums:
    title: Addenda
    output: true
    permalink: "/addenda/:year/:month/:day/:title:output_ext"
  people:
    title: People
    output: true
  posts:
    title: Posts
    output: true
  reports:
    title: Reports
    output: true
    permalink: "/reports/:year/:month/:day/:title:output_ext"
  uploads:
    title: Uploads
    output: true
description: This is the GitHub Repository of the Royal Society DELVE Initiative
baseurl: ''
url: http://rs-delve.github.io
github_username: rs-delve
github:
  edit: true
  repository: rs-delve.github.io
future: true
theme: minima
plugins:
- jekyll-feed
